other:
  join-message:
    - "&7&m---------------------------------"
    - "&7Welcome to &bdamt's practice core!"
    - " "
    - "&b&lDiscord&7 | damt#0886"
    - "&b&lTelegram&7 | @therealdamt"
    - "&7&m---------------------------------"

settings:
  use-placeholder: true
  required-wins: 10

mongo:
  host: "localhost"
  port: 27017
  auth:
    enabled: false
    database: "admin"
    username: ""
    password: ""

scoreboard:
  title: "&b&lPractice"
  normal:
    - "&7&m--------------------"
    - "&b&lPlayer Name&7: {player}"
    - " "
    - "&b&lWins&7: {wins}"
    - "&b&lLoses&7: {loses}"
    - "&b&lCoins&7: {coins}"
    - " "
    - "&b&lPlayers Online&7: {online}"
    - "&b&lPlayers In Queue &7: {queue}"
    - "&7&m--------------------"
  in-game:
    - "&7&m--------------------"
    - "&b&lYou&7: {player} &b({player_ping})"
    - "&b&lOpponent&7: {opponent} &b({opponent_ping}"
    - " "
    - "&b&lKit&7: {kit}"
    - "&7&m--------------------"
